apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-mvp-component-pyec
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/redhat-appstudio-qe/test-images@sha256:a0dfa12ef10b1188ff32619a46c0f73884053e139dc003641dca7c1d457a8ea0
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
